Transaction test still needs fixing (config)
testMakeProductTransaction(ar.edu.itba.services.PostServiceImplTest): Failed to load ApplicationContext

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [ar.edu.itba.services.TestConfig]; nested exception is java.io.FileNotFoundException: class path resource [ar/edu/itba/paw/interfaces/UserService.class] cannot be opened because it does not exist